set(_lh_target "${LONEHASH_TARGET_ID}")
if(_lh_target STREQUAL "" AND NOT "$ENV{LONEHASH_TARGET_ID}" STREQUAL "")
  set(_lh_target "$ENV{LONEHASH_TARGET_ID}")
endif()
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES LONEHASH_TARGET_ID)
if(_lh_target STREQUAL "")
  message(FATAL_ERROR "LONEHASH_TARGET_ID is required for cross presets")
endif()

function(_lh_require_compiler path)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "required compiler is unavailable: ${path}")
  endif()
  set(CMAKE_C_COMPILER
      "${path}"
      CACHE FILEPATH "target C compiler" FORCE)
endfunction()

function(_lh_prefix_compiler env_name compiler_name)
  set(prefix "$ENV{${env_name}}")
  if(prefix STREQUAL "")
    message(FATAL_ERROR "${env_name} must point at a ${_lh_target} toolchain")
  endif()
  _lh_require_compiler("${prefix}/bin/${compiler_name}")
endfunction()

if(_lh_target STREQUAL "x86_64-linux-gnu")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR x86_64)
  _lh_require_compiler("/usr/bin/cc")
elseif(_lh_target STREQUAL "x86_64-linux-musl")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR x86_64)
  _lh_prefix_compiler("CPKT_X86_64_MUSL_PREFIX" "x86_64-linux-musl-gcc")
elseif(_lh_target STREQUAL "aarch64-linux-gnu")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR aarch64)
  if(DEFINED ENV{CPKT_AARCH64_GNU_PREFIX})
    _lh_prefix_compiler("CPKT_AARCH64_GNU_PREFIX" "aarch64-linux-gnu-gcc")
  else()
    _lh_require_compiler("/usr/bin/aarch64-linux-gnu-gcc")
  endif()
elseif(_lh_target STREQUAL "aarch64-linux-musl")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR aarch64)
  _lh_prefix_compiler("CPKT_AARCH64_MUSL_PREFIX" "aarch64-linux-musl-gcc")
elseif(_lh_target STREQUAL "armhf-linux-gnu")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR arm)
  if(DEFINED ENV{CPKT_ARMHF_GNU_PREFIX})
    _lh_prefix_compiler("CPKT_ARMHF_GNU_PREFIX" "arm-linux-gnueabihf-gcc")
  else()
    _lh_require_compiler("/usr/bin/arm-linux-gnueabihf-gcc")
  endif()
elseif(_lh_target STREQUAL "armhf-linux-musl")
  set(CMAKE_SYSTEM_NAME Linux)
  set(CMAKE_SYSTEM_PROCESSOR arm)
  _lh_prefix_compiler("CPKT_ARMHF_MUSL_PREFIX" "arm-linux-musleabihf-gcc")
elseif(_lh_target STREQUAL "arm64-apple-darwin")
  set(_lh_osxcross "$ENV{OSXCROSS_ROOT}")
  set(_lh_host "$ENV{CPKT_OSXCROSS_HOST}")
  if(_lh_osxcross STREQUAL "")
    set(_lh_osxcross "$ENV{HOME}/.local/cross/osxcross")
  endif()
  if(_lh_host STREQUAL "")
    set(_lh_host "arm64-apple-darwin25")
  endif()
  set(CMAKE_SYSTEM_NAME Darwin)
  set(CMAKE_SYSTEM_PROCESSOR arm64)
  _lh_require_compiler("${_lh_osxcross}/bin/${_lh_host}-clang")
  set(CMAKE_LINKER
      "${_lh_osxcross}/bin/${_lh_host}-ld"
      CACHE FILEPATH "Darwin target linker" FORCE)
  if(NOT EXISTS "${CMAKE_LINKER}")
    message(FATAL_ERROR "required Darwin linker is unavailable: ${CMAKE_LINKER}")
  endif()
  set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=${CMAKE_LINKER}")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=${CMAKE_LINKER}")
  set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=${CMAKE_LINKER}")
else()
  message(FATAL_ERROR "unsupported LONEHASH_TARGET_ID=${_lh_target}")
endif()
